//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientSessionState.WebServiceSessionState {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebServiceSessionState.SessionStateWebServiceSoap")]
    public interface SessionStateWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Toplam", ReplyAction="*")]
        int Toplam(int sayi1, int sayi2);
        
        // CODEGEN: Generating message contract since element name HesaplamayıGetirResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HesaplamayıGetir", ReplyAction="*")]
        ClientSessionState.WebServiceSessionState.HesaplamayıGetirResponse HesaplamayıGetir(ClientSessionState.WebServiceSessionState.HesaplamayıGetirRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HesaplamayıGetirRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HesaplamayıGetir", Namespace="http://tempuri.org/", Order=0)]
        public ClientSessionState.WebServiceSessionState.HesaplamayıGetirRequestBody Body;
        
        public HesaplamayıGetirRequest() {
        }
        
        public HesaplamayıGetirRequest(ClientSessionState.WebServiceSessionState.HesaplamayıGetirRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HesaplamayıGetirRequestBody {
        
        public HesaplamayıGetirRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HesaplamayıGetirResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HesaplamayıGetirResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientSessionState.WebServiceSessionState.HesaplamayıGetirResponseBody Body;
        
        public HesaplamayıGetirResponse() {
        }
        
        public HesaplamayıGetirResponse(ClientSessionState.WebServiceSessionState.HesaplamayıGetirResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HesaplamayıGetirResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientSessionState.WebServiceSessionState.ArrayOfString HesaplamayıGetirResult;
        
        public HesaplamayıGetirResponseBody() {
        }
        
        public HesaplamayıGetirResponseBody(ClientSessionState.WebServiceSessionState.ArrayOfString HesaplamayıGetirResult) {
            this.HesaplamayıGetirResult = HesaplamayıGetirResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SessionStateWebServiceSoapChannel : ClientSessionState.WebServiceSessionState.SessionStateWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SessionStateWebServiceSoapClient : System.ServiceModel.ClientBase<ClientSessionState.WebServiceSessionState.SessionStateWebServiceSoap>, ClientSessionState.WebServiceSessionState.SessionStateWebServiceSoap {
        
        public SessionStateWebServiceSoapClient() {
        }
        
        public SessionStateWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SessionStateWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SessionStateWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SessionStateWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Toplam(int sayi1, int sayi2) {
            return base.Channel.Toplam(sayi1, sayi2);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientSessionState.WebServiceSessionState.HesaplamayıGetirResponse ClientSessionState.WebServiceSessionState.SessionStateWebServiceSoap.HesaplamayıGetir(ClientSessionState.WebServiceSessionState.HesaplamayıGetirRequest request) {
            return base.Channel.HesaplamayıGetir(request);
        }
        
        public ClientSessionState.WebServiceSessionState.ArrayOfString HesaplamayıGetir() {
            ClientSessionState.WebServiceSessionState.HesaplamayıGetirRequest inValue = new ClientSessionState.WebServiceSessionState.HesaplamayıGetirRequest();
            inValue.Body = new ClientSessionState.WebServiceSessionState.HesaplamayıGetirRequestBody();
            ClientSessionState.WebServiceSessionState.HesaplamayıGetirResponse retVal = ((ClientSessionState.WebServiceSessionState.SessionStateWebServiceSoap)(this)).HesaplamayıGetir(inValue);
            return retVal.Body.HesaplamayıGetirResult;
        }
    }
}
